# Generated by Django 3.2.9 on 2021-11-22 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_capturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geolocation_latitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('geolocation_longitude', models.DecimalField(decimal_places=4, max_digits=9)),
                ('captured_date', models.DateTimeField()),
                ('capturer_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='photos.capturer')),
                ('image_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='photos.image')),
                ('tags', models.ManyToManyField(to='photos.Tag')),
            ],
        ),
    ]
