# Generated by Django 3.2.9 on 2021-11-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20211122_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='tags',
            field=models.ManyToManyField(blank=True, to='photos.Tag'),
        ),
    ]
