# Generated by Django 3.2.9 on 2021-11-22 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20211122_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
