# Generated by Django 3.2.9 on 2021-11-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20211122_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
