# Generated by Django 3.2.9 on 2021-11-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_alter_image_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='reference',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.TextField(default='Unknown'),
        ),
    ]
