# Generated by Django 3.2.9 on 2021-11-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_auto_20211122_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='geolocation_latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='geolocation_longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
