# Generated by Django 3.2.9 on 2021-12-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0014_auto_20211122_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='name',
            field=models.CharField(default='None', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='tags',
            field=models.ManyToManyField(default='None', to='photos.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='None', max_length=200, unique=True),
        ),
    ]
