# Generated by Django 3.2.9 on 2021-12-17 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0016_image_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='capturer_id',
        ),
        migrations.DeleteModel(
            name='Capturer',
        ),
    ]
