# Generated by Django 3.2.9 on 2021-12-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0017_auto_20211217_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(default='None', unique=True),
        ),
    ]
