# Generated by Django 3.2.9 on 2021-11-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_alter_album_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='tags',
            field=models.ManyToManyField(default='Unknown', to='photos.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='Unknown', max_length=200, unique=True),
        ),
    ]
